#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CryptoTouch.Resource", IsApplication=true)]

namespace CryptoTouch
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int ButtonHighlight = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int error = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fingerprint = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fingerprint_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int plus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rcPannel = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int save = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int deleteButton = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int editText = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int fingerprintIcon = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int layout = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int leftColumn = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int newNoteButton = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int rightColumn = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int saveNoteButton = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int textView = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NotePage = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CryptoTouch_NoOrange = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
